//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theFood.Domain.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.Comment = new HashSet<Comment>();
            this.Ingridient = new HashSet<Ingridient>();
            this.UserRecipe = new HashSet<UserRecipe>();
            this.Picture = new HashSet<Picture>();
            this.UserFavoritRecipe = new HashSet<UserFavoritRecipe>();
        }
    
        public int Id { get; set; }
        public string Text { get; set; }
        public int LikeDislike { get; set; }
        public int RatingRecipe { get; set; }
        public System.DateTime CookingTime { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int CategoryRecipeId { get; set; }
        public int EatingTimeId { get; set; }
        public string UniqueName { get; set; }
    
        public virtual CategoryRecipe CategoryRecipe { get; set; }
        public virtual EatingTime EatingTime1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingridient> Ingridient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRecipe> UserRecipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Picture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFavoritRecipe> UserFavoritRecipe { get; set; }
    }
}
